;;; Problem 6.1
(define (yacht-club)
  (define maryann 1)
  (define gabrielle 2)
  (define lorna 3)
  (define rosalind 4)
  (define melissa 5)
  (let ((moore_daughter (amb maryann gabrielle lorna rosalind melissa))
	(moore_yacht (amb maryann gabrielle lorna rosalind melissa))
	(hood_daughter (amb maryann gabrielle lorna rosalind melissa))
	(hood_yacht (amb maryann gabrielle lorna rosalind melissa))
	(downing_daughter (amb maryann gabrielle lorna rosalind melissa))
	(downing_yacht (amb maryann gabrielle lorna rosalind melissa))
	(hall_daughter (amb maryann gabrielle lorna rosalind melissa))
	(hall_yacht (amb maryann gabrielle lorna rosalind melissa))
	(parker_daughter (amb maryann gabrielle lorna rosalind melissa))
	(parker_yacht (amb maryann gabrielle lorna rosalind melissa)))
    (define (yacht-owned-by-father-of d)
      (cond ((= moore_daughter d) moore_yacht)
	    ((= hood_daughter d) hood_yacht)
	    ((= downing_daughter d) downing_yacht)
	    ((= hall_daughter d) hall_yacht)
	    ((= parker_daughter d) parker_yacht)
	    (else (amb))))
    ;(require (= moore_daughter maryann))
    (require (= hood_daughter melissa))
    (require (= hood_yacht gabrielle))
    (require (= moore_yacht lorna))
    (require (= hall_yacht rosalind))
    (require (= downing_yacht melissa))
    (require (distinct? (list moore_daughter hood_daughter downing_daughter hall_daughter parker_daughter)))
    (require (distinct? (list moore_yacht hood_yacht downing_yacht hall_yacht parker_yacht)))
    (require (not (= hall_daughter rosalind)))
    (require (not (= parker_daughter gabrielle)))
    (require (= (yacht-owned-by-father-of gabrielle) parker_daughter))
    (pp (list (list 'moore_daughter moore_daughter)
	  (list 'hood_daughter hood_daughter)
	  (list 'downing_daughter downing_daughter)
	  (list 'hall_daughter hall_daughter)
	  (list 'parker_daughter parker_daughter)))
    (amb)))

;(with-depth-first-schedule yacht-club)
;Value: ((moore_daughter 1) (hood_daughter 5) (downing_daughter 3) (hall_daughter 2) (parker_daughter 4))

;;; Problem 6.2
(define (snark-hunt tree)
  (call-with-current-continuation
   (lambda (t_exit)
     (or (let lp ((tree tree))
	   (cond ((pair? tree) (or (lp (car tree)) (lp (cdr tree))))
	     ((eqv? tree 'snark) (t_exit #t)))
	   #f)
	 #f))))

;(snark-hunt '(((a b c) d (e f)) g (((snark . "oops") h) (i . j))))
; Value: #t
;(snark-hunt '(((a b c) d (e f)) g (((snak . "oops") h) (i . j))))
; Value: #f
